### ISSUE TITLE
NYC facilities data needed in nycgis_v2 database

### ISSUE THREAD

**Issue by shannonthol** [tnc-ny-science/NYC_PostGISDB_Setup#4]
Need to add NYC facilities data to nycgis_v2 database
Name: Facilities Database - Shapefile
URL: https://data.cityofnewyork.us/City-Government/Facilities-Database-Shapefile/2fpa-bnsx

**Comment by mtreg** [comment]
Data source added in [this commit](https://github.com/tnc-ny-science/NYC_PostGISDB_Setup/commit/6d4f1f129882b39525fc143fbcf9c8e4877b45bc)
